apiVersion: v1
kind: Service
metadata:
  name: order-management-api
  labels:
    app: order-management-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8081
    protocol: TCP
    name: https
  selector:
    app: order-management-api


